// ============================================================
// Doordarshan Electronics — Product Catalog
// Auto-seeded from: DOORDARSHAN ELECTRONIC 2017-2026_Stock_Summary.csv
// Prices are placeholder — update via Admin Panel
// ============================================================

const PRODUCTS = [
  // ─── LED TELEVISIONS ────────────────────────────────────────
  {
    id: 1,
    name: 'Bush 43" QLED Smart TV',
    brand: 'Bush',
    category: 'tv',
    subcategory: '43-inch',
    type: ['QLED', 'Smart TV', '4K'],
    model: 'BT QLED 1/8',
    mrp: 36990,
    price: 29999,
    stock: 1,
    size: 43,
    rating: 4.0,
    reviews: 6,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'QLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Bush 43" QLED Smart TV with vibrant colours and Android smart features.',
  },
  {
    id: 2,
    name: 'Hisense 43" 4K Smart LED TV',
    brand: 'Hisense',
    category: 'tv',
    subcategory: '43-inch',
    type: ['4K', 'Smart TV'],
    model: '43E4Q',
    mrp: 32990,
    price: 26499,
    stock: 1,
    size: 43,
    rating: 4.2,
    reviews: 15,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (VIDAA)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Hisense 43E4Q 4K Smart LED TV — stunning picture quality at an unbeatable price.',
  },
  {
    id: 3,
    name: 'Hisense 43" QLED 4K Smart TV',
    brand: 'Hisense',
    category: 'tv',
    subcategory: '43-inch',
    type: ['QLED', '4K', 'Smart TV'],
    model: '43Q6Q',
    mrp: 38990,
    price: 31999,
    stock: 2,
    size: 43,
    rating: 4.3,
    reviews: 22,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'QLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (VIDAA)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Hisense 43Q6Q QLED — Quantum Dot technology for richer, more realistic colours.',
  },
  {
    id: 4,
    name: 'Hisense 55" 4K QLED Smart TV',
    brand: 'Hisense',
    category: 'tv',
    subcategory: '55-inch',
    type: ['QLED', '4K', 'Smart TV'],
    model: '55A6Q',
    mrp: 54990,
    price: 44999,
    stock: 1,
    size: 55,
    rating: 4.3,
    reviews: 11,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'QLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (VIDAA)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Hisense 55A6Q QLED — immersive 55-inch entertainment with Dolby Vision.',
  },
  {
    id: 5,
    name: 'Hisense 43" Smart LED TV',
    brand: 'Hisense',
    category: 'tv',
    subcategory: '43-inch',
    type: ['Smart TV', 'Full HD'],
    model: '43E4S',
    mrp: 28990,
    price: 23499,
    stock: 5,
    size: 43,
    rating: 4.1,
    reviews: 34,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': 'Full HD 1080p',
      'Smart TV': 'Yes (VIDAA)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '2',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Hisense 43E4S Full HD Smart LED TV — value for money with smart connectivity.',
  },
  {
    id: 6,
    name: 'Hisense 58" 4K QLED Smart TV',
    brand: 'Hisense',
    category: 'tv',
    subcategory: '58-inch',
    type: ['QLED', '4K', 'Smart TV'],
    model: '58A6Q',
    mrp: 62990,
    price: 51999,
    stock: 1,
    size: 58,
    rating: 4.4,
    reviews: 9,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '58 Inches',
      'Display Type': 'QLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (VIDAA)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Hisense 58A6Q — the cinematic 58-inch QLED experience at home.',
  },
  {
    id: 7,
    name: 'Hisense 65" ULED 4K Smart TV',
    brand: 'Hisense',
    category: 'tv',
    subcategory: '65-inch',
    type: ['ULED', '4K', 'Smart TV'],
    model: '65U7Q',
    mrp: 89990,
    price: 74999,
    stock: 1,
    size: 65,
    rating: 4.5,
    reviews: 7,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '65 Inches',
      'Display Type': 'ULED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (VIDAA)',
      'Refresh Rate': '120 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'Dolby Vision': 'Yes',
      'Warranty': '1 Year',
    },
    description: 'Hisense 65U7Q ULED — flagship 65" with 120Hz and Dolby Vision.',
  },
  {
    id: 8,
    name: 'LG 50" 4K Ultra HD Smart LED TV',
    brand: 'LG',
    category: 'tv',
    subcategory: '50-inch',
    type: ['4K', 'Smart TV'],
    model: '50UP7550PTZ',
    mrp: 57990,
    price: 46999,
    stock: 1,
    size: 50,
    rating: 4.4,
    reviews: 18,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '50 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (webOS)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'HDR': 'HDR10 Pro',
      'Warranty': '1 Year',
    },
    description: 'LG 50UP7550PTZ — webOS Smart TV with Filmmaker Mode and AI ThinQ.',
  },
  {
    id: 9,
    name: 'LG 65" 4K Ultra HD Smart LED TV',
    brand: 'LG',
    category: 'tv',
    subcategory: '65-inch',
    type: ['4K', 'Smart TV'],
    model: '65UQ7550PSF',
    mrp: 84990,
    price: 69999,
    stock: 1,
    size: 65,
    rating: 4.5,
    reviews: 12,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '65 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (webOS)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'HDR': 'HDR10 Pro',
      'Warranty': '1 Year',
    },
    description: 'LG 65UQ7550PSF — large-screen brilliance with LG webOS and AI sound.',
  },
  {
    id: 10,
    name: 'Metz 43" 4K UHD Smart LED TV',
    brand: 'Metz',
    category: 'tv',
    subcategory: '43-inch',
    type: ['4K', 'Smart TV'],
    model: '43MUE7600',
    mrp: 34990,
    price: 27999,
    stock: 4,
    size: 43,
    rating: 4.2,
    reviews: 19,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Metz 43MUE7600 — German engineering meets Indian entertainment.',
  },
  {
    id: 11,
    name: 'Metz 50" 4K UHD Smart LED TV',
    brand: 'Metz',
    category: 'tv',
    subcategory: '50-inch',
    type: ['4K', 'Smart TV'],
    model: '50MUE7600',
    mrp: 44990,
    price: 36999,
    stock: 1,
    size: 50,
    rating: 4.2,
    reviews: 8,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '50 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Metz 50MUE7600 — premium 50" 4K experience at an accessible price.',
  },
  {
    id: 12,
    name: 'Metz 55" 4K Smart LED TV',
    brand: 'Metz',
    category: 'tv',
    subcategory: '55-inch',
    type: ['4K', 'Smart TV'],
    model: '55MTD4050',
    mrp: 54990,
    price: 44999,
    stock: 1,
    size: 55,
    rating: 4.2,
    reviews: 5,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Metz 55MTD4050 — stunning visuals in a premium 55-inch build.',
  },
  {
    id: 13,
    name: 'Metz 75" 4K UHD Smart LED TV',
    brand: 'Metz',
    category: 'tv',
    subcategory: '75-inch',
    type: ['4K', 'Smart TV'],
    model: '75MUE7600',
    mrp: 1,
    price: 119999,
    stock: 1,
    size: 75,
    rating: 4.4,
    reviews: 4,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '75 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '4',
      'USB Ports': '3',
      'Warranty': '1 Year',
    },
    description: 'Metz 75MUE7600 — the ultimate home theatre at 75 inches.',
  },
  {
    id: 14,
    name: 'Bush 55" Smart LED TV',
    brand: 'Bush',
    category: 'tv',
    subcategory: '55-inch',
    type: ['Smart TV', '4K'],
    model: 'BUSH 55" LED SMART',
    mrp: 47990,
    price: 39999,
    stock: 1,
    size: 55,
    rating: 4.0,
    reviews: 3,
    isNew: true,
    isFeatured: false,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'New Bush 55" Smart LED — stylish smart TV for modern homes.',
  },
  {
    id: 15,
    name: 'OnePlus 50" Y1S Pro 4K Smart LED TV',
    brand: 'OnePlus',
    category: 'tv',
    subcategory: '50-inch',
    type: ['4K', 'Smart TV'],
    model: '50Y1S PRO',
    mrp: 49990,
    price: 39999,
    stock: 1,
    size: 50,
    rating: 4.3,
    reviews: 28,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '50 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android 11)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'OnePlus 50Y1S Pro — Gamma Engine, 4K HDR and a lightning-fast OS.',
  },
  {
    id: 16,
    name: 'PHX 32" LED TV',
    brand: 'PHX',
    category: 'tv',
    subcategory: '32-inch',
    type: ['HD Ready'],
    model: 'P3200 N',
    mrp: 12990,
    price: 9999,
    stock: 1,
    size: 32,
    rating: 3.8,
    reviews: 4,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '32 Inches',
      'Display Type': 'LED',
      'Resolution': 'HD Ready 720p',
      'Smart TV': 'No',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '2',
      'USB Ports': '1',
      'Warranty': '1 Year',
    },
    description: 'PHX P3200N — compact, budget-friendly 32" for bedrooms.',
  },
  {
    id: 17,
    name: 'Samsung 55" QLED 4K Smart TV',
    brand: 'Samsung',
    category: 'tv',
    subcategory: '55-inch',
    type: ['QLED', '4K', 'Smart TV'],
    model: 'QA55Q8FAAULXL',
    mrp: 99990,
    price: 82999,
    stock: 1,
    size: 55,
    rating: 4.6,
    reviews: 45,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'QLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Tizen)',
      'Refresh Rate': '120 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'HDR': 'HDR10+',
      'Warranty': '1 Year',
    },
    description: 'Samsung 55" Q8F QLED — Direct Full Array, 2000-nit brightness, HDR10+.',
  },
  {
    id: 18,
    name: 'Samsung 65" Crystal 4K Smart LED TV',
    brand: 'Samsung',
    category: 'tv',
    subcategory: '65-inch',
    type: ['4K', 'Smart TV'],
    model: 'UA65CU7700KLXL',
    mrp: 91990,
    price: 74999,
    stock: 1,
    size: 65,
    rating: 4.5,
    reviews: 33,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '65 Inches',
      'Display Type': 'Crystal 4K LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Tizen)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '1',
      'HDR': 'HDR10+',
      'Warranty': '1 Year',
    },
    description: 'Samsung 65CU7700 Crystal 4K — wide viewing angle and Motion Xcelerator.',
  },
  {
    id: 19,
    name: 'Samsung 55" 4K Ultra HD Smart LED TV',
    brand: 'Samsung',
    category: 'tv',
    subcategory: '55-inch',
    type: ['4K', 'Smart TV'],
    model: 'UA55U8100FULXL',
    mrp: 79990,
    price: 64999,
    stock: 2,
    size: 55,
    rating: 4.4,
    reviews: 21,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Tizen)',
      'Refresh Rate': '120 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Samsung 55U8100 — 4K + Motion Rate 240 for ultra-smooth action.',
  },
  {
    id: 20,
    name: 'Skyworth 40" Full HD Smart LED TV',
    brand: 'Skyworth',
    category: 'tv',
    subcategory: '40-inch',
    type: ['Smart TV', 'Full HD'],
    model: '40E4000S',
    mrp: 22990,
    price: 17999,
    stock: 1,
    size: 40,
    rating: 3.9,
    reviews: 7,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '40 Inches',
      'Display Type': 'LED',
      'Resolution': 'Full HD 1080p',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '2',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Skyworth 40E4000S — affordable 40" FHD Smart TV for budget-conscious buyers.',
  },
  {
    id: 21,
    name: 'Skyworth 43" 4K UHD Smart LED TV',
    brand: 'Skyworth',
    category: 'tv',
    subcategory: '43-inch',
    type: ['4K', 'Smart TV'],
    model: '43UB7550',
    mrp: 35990,
    price: 28999,
    stock: 1,
    size: 43,
    rating: 4.1,
    reviews: 6,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'Skyworth 43UB7550 — sleek 43" 4K Smart TV with Dolby Audio.',
  },
  {
    id: 22,
    name: 'Sony Bravia 43" 4K Ultra HD Smart LED TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '43-inch',
    type: ['4K', 'Smart TV'],
    model: 'K-43S22M2',
    mrp: 54990,
    price: 42999,
    stock: 5,
    size: 43,
    rating: 4.5,
    reviews: 67,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'HDR': 'HDR10, HLG',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony Bravia K-43S22M2 — Google TV, 4K HDR, X1 Processor for sharp detail.',
  },
  {
    id: 23,
    name: 'Sony Bravia 43" 4K Google TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '43-inch',
    type: ['4K', 'Smart TV', 'Google TV'],
    model: 'K-43S25',
    mrp: 58990,
    price: 46999,
    stock: 1,
    size: 43,
    rating: 4.5,
    reviews: 42,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-43S25 — latest 2025 Google TV with Dolby Vision & Atmos.',
  },
  {
    id: 24,
    name: 'Sony Bravia 43" 4K Google TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '43-inch',
    type: ['4K', 'Smart TV', 'Google TV'],
    model: 'K-43S25M2',
    mrp: 60990,
    price: 48999,
    stock: 3,
    size: 43,
    rating: 4.6,
    reviews: 29,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Processor': 'X1 4K HDR',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-43S25M2 — upgraded X1 4K HDR processor with refined Google TV.',
  },
  {
    id: 25,
    name: 'Sony Bravia 50" 4K Ultra HD Smart LED TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '50-inch',
    type: ['4K', 'Smart TV'],
    model: 'K-50S22M2',
    mrp: 69990,
    price: 54999,
    stock: 2,
    size: 50,
    rating: 4.5,
    reviews: 38,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '50 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'HDR': 'HDR10, HLG',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-50S22M2 — step up to 50" Bravia 4K with Google TV.',
  },
  {
    id: 26,
    name: 'Sony Bravia 50" 4K Google TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '50-inch',
    type: ['4K', 'Smart TV', 'Google TV'],
    model: 'K-50S25M2',
    mrp: 74990,
    price: 58999,
    stock: 1,
    size: 50,
    rating: 4.6,
    reviews: 17,
    isNew: true,
    isFeatured: false,
    specs: {
      'Screen Size': '50 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-50S25M2 — 2025 Google TV model with Dolby Vision and wide colour gamut.',
  },
  {
    id: 27,
    name: 'Sony Bravia 55" 4K Google TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '55-inch',
    type: ['4K', 'Smart TV', 'Google TV'],
    model: 'K-55S25M2',
    mrp: 84990,
    price: 67999,
    stock: 4,
    size: 55,
    rating: 4.6,
    reviews: 52,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Processor': 'X1 4K HDR',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-55S25M2 — best-selling 55" Bravia with Dolby Vision & Atmos in 2025.',
  },
  {
    id: 28,
    name: 'Sony Bravia 55" OLED 4K Google TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '55-inch',
    type: ['OLED', '4K', 'Smart TV', 'Google TV'],
    model: 'K-55XR55A',
    mrp: 1,
    price: 149999,
    stock: 2,
    size: 55,
    rating: 4.8,
    reviews: 14,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'OLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '120 Hz',
      'HDMI Ports': '4 (HDMI 2.1)',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Processor': 'XR Cognitive',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-55XR55A OLED Bravia — XR Cognitive Processor, true-to-life colours, premium audio.',
  },
  {
    id: 29,
    name: 'Sony Bravia 65" 4K Google TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '65-inch',
    type: ['4K', 'Smart TV', 'Google TV'],
    model: 'K-65S25M2',
    mrp: 109990,
    price: 87999,
    stock: 2,
    size: 65,
    rating: 4.6,
    reviews: 31,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '65 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Processor': 'X1 4K HDR',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-65S25M2 — flagship 65" Bravia 2025 Google TV with cinema-grade visuals.',
  },
  {
    id: 30,
    name: 'Sony Bravia 65" 4K Smart LED TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '65-inch',
    type: ['4K', 'Smart TV'],
    model: 'K-65S30',
    mrp: 99990,
    price: 81999,
    stock: 1,
    size: 65,
    rating: 4.5,
    reviews: 23,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '65 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'HDR': 'HDR10, HLG',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-65S30 — premium 65" for living room entertainment.',
  },
  {
    id: 31,
    name: 'Sony Bravia 55" OLED 4K TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '55-inch',
    type: ['OLED', '4K', 'Smart TV', 'Google TV'],
    model: 'K-55XR35M2',
    mrp: 1,
    price: 129999,
    stock: 2,
    size: 55,
    rating: 4.7,
    reviews: 9,
    isNew: true,
    isFeatured: false,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'OLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '120 Hz',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-55XR35M2 OLED — stunning picture quality with perfect blacks.',
  },
  {
    id: 32,
    name: 'Sony Bravia 65" OLED 4K TV',
    brand: 'Sony',
    category: 'tv',
    subcategory: '65-inch',
    type: ['OLED', '4K', 'Smart TV', 'Google TV'],
    model: 'K-65XR35M2',
    mrp: 1,
    price: 169999,
    stock: 1,
    size: 65,
    rating: 4.8,
    reviews: 6,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '65 Inches',
      'Display Type': 'OLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '120 Hz',
      'HDMI Ports': '4 (HDMI 2.1)',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Processor': 'XR Cognitive',
      'Warranty': '1 Year Sony',
    },
    description: 'Sony K-65XR35M2 OLED — 65" XR Cognitive processor with ultimate contrast.',
  },
  {
    id: 33,
    name: 'TCL 43" 4K Smart LED TV',
    brand: 'TCL',
    category: 'tv',
    subcategory: '43-inch',
    type: ['4K', 'Smart TV'],
    model: '43P6L',
    mrp: 36990,
    price: 28999,
    stock: 3,
    size: 43,
    rating: 4.2,
    reviews: 44,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android 11)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'HDR': 'HDR10',
      'Warranty': '1 Year',
    },
    description: 'TCL 43P6L — high-value 43" 4K Android TV with AiPQ Engine.',
  },
  {
    id: 34,
    name: 'TCL 43" 4K Smart LED TV',
    brand: 'TCL',
    category: 'tv',
    subcategory: '43-inch',
    type: ['4K', 'Smart TV'],
    model: '43P6K',
    mrp: 34990,
    price: 27999,
    stock: 1,
    size: 43,
    rating: 4.2,
    reviews: 19,
    isNew: false,
    isFeatured: false,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Warranty': '1 Year',
    },
    description: 'TCL 43P6K — solid performer with crisp 4K visuals and Android TV.',
  },
  {
    id: 35,
    name: 'TCL 43" QLED 4K Smart TV',
    brand: 'TCL',
    category: 'tv',
    subcategory: '43-inch',
    type: ['QLED', '4K', 'Smart TV'],
    model: '43S5K',
    mrp: 41990,
    price: 33999,
    stock: 3,
    size: 43,
    rating: 4.3,
    reviews: 27,
    isNew: true,
    isFeatured: true,
    specs: {
      'Screen Size': '43 Inches',
      'Display Type': 'QLED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Google TV)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'HDR': 'Dolby Vision, HDR10',
      'Warranty': '1 Year',
    },
    description: 'TCL 43S5K QLED Google TV — Quantum Dot meets Google TV at a great price.',
  },
  {
    id: 36,
    name: 'TCL 55" 4K Smart LED TV',
    brand: 'TCL',
    category: 'tv',
    subcategory: '55-inch',
    type: ['4K', 'Smart TV'],
    model: '55P6L',
    mrp: 51990,
    price: 41999,
    stock: 3,
    size: 55,
    rating: 4.3,
    reviews: 36,
    isNew: false,
    isFeatured: true,
    specs: {
      'Screen Size': '55 Inches',
      'Display Type': 'LED',
      'Resolution': '4K Ultra HD',
      'Smart TV': 'Yes (Android)',
      'Refresh Rate': '60 Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'HDR': 'HDR10',
      'Warranty': '1 Year',
    },
    description: 'TCL 55P6L — 55" 4K entertainment with AiPQ Engine and Dolby Audio.',
  },
];

// ─── Helper Functions ────────────────────────────────────────

function getProductById(id) {
  return PRODUCTS.find(p => p.id === id) || null;
}

function getProductsByCategory(category, filters = {}) {
  return PRODUCTS.filter(p => {
    if (p.category !== category) return false;
    if (filters.brand && p.brand !== filters.brand) return false;
    if (filters.subcategory && p.subcategory !== filters.subcategory) return false;
    if (filters.type && !p.type.includes(filters.type)) return false;
    if (filters.maxPrice && p.price > filters.maxPrice) return false;
    if (filters.minPrice && p.price < filters.minPrice) return false;
    return true;
  });
}

function getFeaturedProducts(limit = 8) {
  return PRODUCTS.filter(p => p.isFeatured).slice(0, limit);
}

function getNewArrivals(limit = 8) {
  return PRODUCTS.filter(p => p.isNew).slice(0, limit);
}

function formatPrice(num) {
  if (num <= 1) return 'Call for Price';
  return '₹' + num.toLocaleString('en-IN');
}

function getDiscount(mrp, price) {
  if (mrp <= 1) return null;
  const pct = Math.round(((mrp - price) / mrp) * 100);
  return pct > 0 ? pct : null;
}

// Brand colours for image placeholders
const BRAND_COLORS = {
  Sony:    { bg: '#0033A0', text: '#ffffff' },
  Samsung: { bg: '#1428A0', text: '#ffffff' },
  LG:      { bg: '#A50034', text: '#ffffff' },
  Hisense: { bg: '#E4002B', text: '#ffffff' },
  TCL:     { bg: '#D52B1E', text: '#ffffff' },
  Metz:    { bg: '#2C2C2C', text: '#ffffff' },
  Bush:    { bg: '#005EB8', text: '#ffffff' },
  OnePlus: { bg: '#F5010C', text: '#ffffff' },
  Skyworth:{ bg: '#00529B', text: '#ffffff' },
  PHX:     { bg: '#444444', text: '#ffffff' },
};

function getBrandColor(brand) {
  return BRAND_COLORS[brand] || { bg: '#0B2C6E', text: '#ffffff' };
}
